#!/bin/sh
set -eu

case "$(uname -m)" in
  x86_64) arch_triplet="x86_64-linux-gnu" ;;
  aarch64|arm64) arch_triplet="aarch64-linux-gnu" ;;
  *) arch_triplet="" ;;
esac

library_path="$SNAP/opt/lumyn:$SNAP/opt/lumyn/lib:$SNAP/usr/lib"

if [ -n "$arch_triplet" ]; then
  for dir in \
    "$SNAP/usr/lib/$arch_triplet" \
    "$SNAP/lib/$arch_triplet" \
    "$SNAP/usr/lib/$arch_triplet/pulseaudio" \
    "$SNAP/usr/lib/$arch_triplet/dri"; do
    if [ -d "$dir" ]; then
      library_path="$library_path:$dir"
    fi
  done

  if [ -d "$SNAP/usr/lib/$arch_triplet/dri" ]; then
    export LIBGL_DRIVERS_PATH="$SNAP/usr/lib/$arch_triplet/dri"
  fi
fi

export LD_LIBRARY_PATH="$library_path${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

exec "$SNAP/opt/lumyn/Lumyn" "$@"
